<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_MasterPage.master" AutoEventWireup="true" CodeFile="Admin_View_Contact_US.aspx.cs" Inherits="Admin_View_Contact_US" %>

<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="ajaxToolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <center>
    <asp:Label ID="Label6" runat="server" Font-Bold="True" Font-Italic="True" 
                Font-Size="30pt" Font-Underline="False" Text="Manage Contact US" 
                CssClass="label1-style"></asp:Label>
        <ajaxToolkit:RoundedCornersExtender ID="Label6_RoundedCornersExtender" 
            runat="server" BehaviorID="Label6_RoundedCornersExtender" 
            TargetControlID="Label6" />
        <ajaxToolkit:DropShadowExtender ID="Label6_DropShadowExtender" runat="server" 
            BehaviorID="Label6_DropShadowExtender" TargetControlID="Label6" />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" DataKeyNames="cid" 
        DataSourceID="SqlDataSource1" Height="195px" Width="731px" 
        CssClass="textbox-style" HorizontalAlign="Center">
        <Columns>
            <asp:BoundField DataField="cid" HeaderText="Contact ID" InsertVisible="False" 
                ReadOnly="True" SortExpression="cid" />
            <asp:BoundField DataField="cutype" HeaderText="User Type" 
                SortExpression="cutype" />
            <asp:BoundField DataField="cunm" HeaderText="User Name" SortExpression="cunm" />
            <asp:BoundField DataField="cumno" HeaderText="User Contact No." 
                SortExpression="cumno" />
            <asp:BoundField DataField="cuemail" HeaderText="User E-Mail ID" 
                SortExpression="cuemail" />
            <asp:BoundField DataField="cumsg" HeaderText="User's  Query / Message" 
                SortExpression="cumsg" />
        </Columns>
        <HeaderStyle BackColor="#006666" BorderColor="#99FFCC" BorderStyle="Inset" 
            BorderWidth="3px" Font-Bold="True" HorizontalAlign="Center" 
            VerticalAlign="Middle" />
        <SelectedRowStyle BackColor="#CCFFFF" ForeColor="#006666" />
    </asp:GridView>
    <ajaxToolkit:DropShadowExtender ID="GridView1_DropShadowExtender" 
        runat="server" BehaviorID="GridView1_DropShadowExtender" 
        TargetControlID="GridView1" />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Conn %>" 
        SelectCommand="SELECT * FROM [Contact_US] ORDER BY [cid]"
         DeleteCommand="delete from [Contact_US] where cid=@cid">
            
            <DeleteParameters> 
            <asp:Parameter Name="cid" Type="Int32" />
            
            </DeleteParameters>
            
        </asp:SqlDataSource>

</center>
</asp:Content>

