<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_MasterPage.master" AutoEventWireup="true" CodeFile="Admin_View_FeedBacks.aspx.cs" Inherits="Admin_View_FeedBacks" %>

<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="ajaxToolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <center>
      <asp:Label ID="Label6" runat="server" Font-Bold="True" Font-Italic="True" 
                Font-Size="30pt" Font-Underline="False" Text="Manage Feed Backs" 
                CssClass="label1-style"></asp:Label>

        <ajaxToolkit:RoundedCornersExtender ID="Label6_RoundedCornersExtender" 
            runat="server" BehaviorID="Label6_RoundedCornersExtender" 
            TargetControlID="Label6" />
        <ajaxToolkit:DropShadowExtender ID="Label6_DropShadowExtender" runat="server" 
            BehaviorID="Label6_DropShadowExtender" TargetControlID="Label6" />

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" DataKeyNames="fid" 
        DataSourceID="SqlDataSource1" Height="195px" Width="731px" 
        CssClass="textbox-style" HorizontalAlign="Center">
        <Columns>
            <asp:BoundField DataField="fid" HeaderText="Feed Back ID" InsertVisible="False" 
                ReadOnly="True" SortExpression="fid" />
            <asp:BoundField DataField="futype" HeaderText="User Type" 
                SortExpression="futype" />
            <asp:BoundField DataField="funm" HeaderText="User Name" SortExpression="funm" />
            <asp:BoundField DataField="fumno" HeaderText="User Mobile No." 
                SortExpression="fumno" />
            <asp:BoundField DataField="fuemail" HeaderText="User E-Mail ID" 
                SortExpression="fuemail" />
            <asp:BoundField DataField="fumsg" HeaderText="Feed Back" 
                SortExpression="fumsg" />
        </Columns>
        <HeaderStyle BackColor="#006666" BorderColor="#99FFCC" BorderStyle="Inset" 
            BorderWidth="3px" Font-Bold="True" HorizontalAlign="Center" 
            VerticalAlign="Middle" />
        <SelectedRowStyle BackColor="#CCFFFF" ForeColor="#006666" />
    </asp:GridView>
    <ajaxToolkit:DropShadowExtender ID="GridView1_DropShadowExtender" 
        runat="server" BehaviorID="GridView1_DropShadowExtender" 
        TargetControlID="GridView1" />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Conn %>" 
        SelectCommand="SELECT * FROM [FeedBack] ORDER BY [fid]"
        DeleteCommand="delete from [FeedBack] where fid=@fid">
            
            <DeleteParameters> 
            <asp:Parameter Name="fid" Type="Int32" />
            
            </DeleteParameters>
        </asp:SqlDataSource>

</center>
</asp:Content>

