<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_MasterPage.master" AutoEventWireup="true" CodeFile="Admin_About Us_Principal's Message.aspx.cs" Inherits="Admin_About_Us_Principal_s_Message" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        <strong style="color: rgb(15, 95, 241);">&nbsp;Anand Commerce College<span>&nbsp;</span></strong>has 
        had a glorious past and a rich history of imparting commercial&nbsp; education of a high 
        standard.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p 
        style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        <asp:Image ID="Image5" runat="server" BorderColor="Aqua" BorderStyle="Inset" 
            BorderWidth="5px" Height="256px" ImageAlign="Right" 
            ImageUrl="~/Images/Principal Dr. V.M. Vanhar.jpg" Width="363px" />
        After taking over the&nbsp;mantle of Principal ship, I take pride in&nbsp;&nbsp; the fact that 
        this institution was shaped by toil and sweat&nbsp;&nbsp; of&nbsp;towering personalities 
        like&nbsp;Pujya Shri Bhaikaka, Shri&nbsp;
    </p>
    <p 
        style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
&nbsp;Bhikhakaka, Shri H M Patel and Dr C L Patel.
    </p>
    <p 
        style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;
        &nbsp;</p>
    <p 
        style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        So 
        it is indeed a challenge to maintain this great legacy.</p>
    <p 
        style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        In 2013 we applied for NAAC re-accreditation and got &quot;A&quot;&nbsp;&nbsp; grade with a CGPA 3.12 
        on a four point scale. </p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        In 2014 the&nbsp;&nbsp; KCG,Gandhinagar,also awarded &quot;A&quot; grade with a 
        CGPA of&nbsp;&nbsp; 3.14. </p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        I am confident that we will improve our standing in the&nbsp;&nbsp; coming 
        years.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        The college will have to go for NAAC Accreditation, third cycle in 2018. 
    </p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        We are 
        on track to achieve a higher grade because our preparations are already under 
        way and with the support , cooperation and encouragement from all the stake 
        holders viz. 
    </p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        The management, the faculty, the students and others, we will 
        achieve greater heights .
    </p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        <br style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <strong style="font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(15, 95, 241); font-weight: bold;">Dr. Vijay M. Vanhar</strong><br 
        style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <strong style="font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(15, 95, 241); font-weight: bold;">Principal</strong>
    </p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
</asp:Content>

