<%@ Page Title="" Language="C#" MasterPageFile="~/Pre_Login_MasterPage.master" AutoEventWireup="true" CodeFile="Pre_Login_About Us_Genesis.aspx.cs" Inherits="Pre_Login_About_Us_Genesis" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">1942:<span>&nbsp;</span></strong>Sardar 
    Patel inspired Bhaikaka (Bhailalbhai Patel) to take up social services for 
    development of rural India.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">1943:</strong><span>&nbsp;</span>Bhaikaka 
    joined Charotar Education Society as Chairman: the idea of establishing Rural 
    University (Vidyapith) was conceived.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">August 1945:</strong><span>&nbsp;</span>Charutar 
    Vidya Mandal was established.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">September 1945:</strong><span>&nbsp;</span>Charotar 
    Grammoddhar Sahkari Mandal was established. Farmers contributed around 500 Acres 
    of lands initially. 
    </p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    Participation of farmers through a scheme of enlightened 
    self-interest: 1/10 of the donated land was returned back to the farmers as a 
    residential plot. 
    </p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    Shri Indulal Yagnik suggested the name of the township: 
    Vallabh Vidyanagar.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">March 1946:</strong><span>&nbsp;</span>Bhaikaka 
    &amp; Bhikhabhai Patel started living in Vallabh Vidyanagar.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">April 1947:</strong><span>&nbsp;</span>Shri 
    Viththalbhai Patel Science College inaugurated by Sardar Patel, and affiliated 
    to Mumbai University. 
    </p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    The V.P.Science College started functioning with first 
    lecture delivered by the then Vice-Chancellor of Mumbai University Justice 
    M.C.Chagla.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">1948:</strong><span>&nbsp;</span>P.G. 
    Programme in M.A. and M.Sc. started in<span>&nbsp;</span><strong>V.P.&amp;R.P.T.P. 
    Science College<span>&nbsp;</span></strong>.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">1949:</strong><span>&nbsp;</span>Colleges of 
    Vidyanagar shifted&nbsp; to Gujarat University.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">31 October 1955:</strong><span>&nbsp;</span>Sardar 
    Vallabhbhai Vidyapith established with Shri Bhaikaka as first Vice-Chancellor.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    <strong style="color: rgb(15, 95, 241);">After October 1968:<span>&nbsp;</span></strong>The 
    University changed&nbsp; its name&nbsp; to Sardar Patel University.</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
<p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;</p>
</asp:Content>

