<%@ Page Title="" Language="C#" MasterPageFile="~/Staff_MasterPage.master" AutoEventWireup="true" CodeFile="Staff_About Us_Mission_Vision_Goal.aspx.cs" Inherits="Staff_About_Us_Mission_Vision_Goal" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <center style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <b class="fa fa-anchor" 
        style="display: inline-block; font: x-large / 1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased; color: rgb(15, 95, 241);">
        <br />&nbsp;<b class="fa fa-bullseye" 
        style="display: inline-block; font: x-large / 1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased; color: rgb(15, 95, 241);"><br />&#x25BA; 
        </b>Mission:</b></center>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    We dedicate ourselves to the continuation of our founders’ vision of 
    scholastically uplifting rural youth along with value education to prepare 
    globally competitive citizens who contribute towards nation building.</p>
    <center style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <b class="fa fa-eye" 
        style="display: inline-block; font: x-large / 1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased; color: rgb(15, 95, 241);">
        <b class="fa fa-bullseye" 
        style="display: inline-block; font: x-large / 1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased; color: rgb(15, 95, 241);">&#x25BA;
        </b>Vision:</b><br />
    </center>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    To educate, empower and prepare globally competitive human resource through 
    knowledge, employability, entrepreneurship skills by creating an environment 
    conducive to learning and research in sciences , and critical thinking there by 
    leading to creation of a strong institution through close affinity with its 
    alumni.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <center style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <b class="fa fa-bullseye" 
        style="display: inline-block; font: x-large / 1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased; color: rgb(15, 95, 241);">
        <span>&nbsp;&#x25BA; </span>Goals:<br /></b>
    </center>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    To create and nourish a stimulating learning environment that ensures a globally 
    relevant education, based on eternal human values.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    To forge and reward excellence in the curricular as well as extra-curricular 
    sectors so as to ensure the scholars’ global competitiveness.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    To tap, nurture and unleash the innovative entrepreneurial abilities of scholars 
    and thereby ensuring lifelong socio-economic value- addition.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    To evoke and embellish the finest traits of human excellence that can dovetail 
    into a sustainable career growth curve.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    To affiliate, associate, liaise or otherwise synergize with any institution 
    body, entity, ethno-cultural Diaspora and the overall global fraternity in any 
    form whatsoever, in support of the above.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
    &nbsp;To initiate, consolidate and extrapolate any objectives, function and 
    activities in support of the above.</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: justify;">
        &nbsp;</p>
    <center style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <b class="fa fa-bullseye" 
        style="display: inline-block; font: x-large / 1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased; color: rgb(15, 95, 241);">
        <span>&nbsp;<br />
        <br /></span>&#x25BA; Core Values:</b><br />
    </center>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
    &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
    &#x2022; Equity</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
    &nbsp;&nbsp;&nbsp;&nbsp;
    &#x2022; Accountability</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
    &#x2022; Diversity</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
    &#x2022; Excellence</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
    &#x2022; Respect</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
    &#x2022; Compassion</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
    <p style="color: rgb(6, 33, 63); font-family: Georgia, &quot;Times New Roman&quot;, Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: large; font-weight: bolder; text-align: center;">
        &nbsp;</p>
</asp:Content>

